package com.aurigo.masterworks.testframework.webUI.pages.budgetManagement.budgetEstimate;

import com.aurigo.masterworks.testframework.utilities.ExcelUtil;
import com.aurigo.masterworks.testframework.utilities.LocatorUtil;
import com.aurigo.masterworks.testframework.utilities.models.grid.Host;
import com.aurigo.masterworks.testframework.webUI.common.*;
import com.aurigo.masterworks.testframework.webUI.constants.enums.*;
import com.aurigo.masterworks.testframework.webUI.generic.*;
import com.aurigo.masterworks.testframework.webUI.pages.planning.PlanningPage;
import com.aurigo.masterworks.testframework.webUI.pages.projects.ProjectsPage;
import org.openqa.selenium.By;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.Select;
import org.testng.asserts.SoftAssert;

import java.io.File;
import java.util.*;

public class BudgetEstimatePage extends ListPage {

    public By budgetEstimatesTab;
    private By budgetEstimateTotal;
    private By libraryPage;
    private By measurementSystemsInLibrary;
    private By measurementSystemDropdown;
    private By budgetEstimateCheckBox;
    private By autoGeneratedForecast;
    private By amountHeader;
    private By budgetEstimateName;
    private By budgetEstimateNameID;
    private By budgetEstimateTypeID;
    private By measurementSystemID;
    private By standardItemListID;
    private By descriptionID;
    private By budgetTemplateButton;
    private By budgetTemplatePicker;
    private By inflationHighlightBEDetailsPage;
    private By inflationHighlightBEListPage;
    private By forecastsDetailsTab;
    private By closeBudgetEstimatePopUp;
    private By budgetEstimateFrameID;

    private Select select;
    private double totalRevenueBudgetEstimate;
    private double totalRevenueBudgetItems;

    private String displayedLabels = ".//span[contains(text(),'%s')]";
    private String mandatoryLabel = ".//span[contains(text(),'%s')]/following-sibling::span[contains(text(),'*')]";
    private String autoPopulatedLabel = ".//td[span[contains(text(),'%s')]]/following-sibling::td/span[contains(@aria-label,'%s')]";

    public BudgetEstimatePage(WebDriver driver) {
        super(driver);

        var locators = LocatorUtil.getLocators("BudgetEstimatePage.json");
        budgetEstimatesTab = locators.get("budgetEstimatesTab");
        budgetEstimateTotal = locators.get("budgetEstimateTotal");
        libraryPage = locators.get("libraryPage");
        measurementSystemsInLibrary = locators.get("measurementSystemsInLibrary");
        measurementSystemDropdown = locators.get("measurementSystemDropdown");
        budgetEstimateCheckBox = locators.get("budgetEstimateCheckBox");
        autoGeneratedForecast = locators.get("autoGeneratedForecast");
        amountHeader = locators.get("amountHeader");
        budgetEstimateName = locators.get("budgetEstimateName");
        budgetEstimateNameID = locators.get("budgetEstimateNameID");
        budgetEstimateTypeID = locators.get("budgetEstimateTypeID");
        measurementSystemID = locators.get("measurementSystemID");
        standardItemListID = locators.get("standardItemListID");
        descriptionID = locators.get("descriptionID");
        budgetTemplateButton = locators.get("budgetTemplateButton");
        budgetTemplatePicker = locators.get("budgetTemplatePicker");
        inflationHighlightBEDetailsPage = locators.get("inflationHighlightBEDetailsPage");
        inflationHighlightBEListPage = locators.get("inflationHighlightBEListPage");
        forecastsDetailsTab = locators.get("forecastsDetailsTab");
        closeBudgetEstimatePopUp = locators.get("closeBudgetEstimatePopUp");
        budgetEstimateFrameID = locators.get("budgetEstimateFrameID");
    }

    /**
     * Method to navigate to Budget Estimate page
     *
     * @return True if navigation is successful, else false.
     */
    public boolean navigateTo() {
        logger().info("Navigating to Budgets");
        navigation.switchFrameToContent();
        waitHelper.waitForPageTabHeaderToBeClickable();
        boolean navigatedToBudgetEstimate = navigation.navigateToFormInLeftPaneTree("Budget Estimates");
        navigation.switchFrameToContent();
        waitHelper.waitForPageTabHeaderToBeClickable();
        return navigatedToBudgetEstimate;
    }

    /**
     * Method to open an existing BE item
     *
     * @param budgetEstimateName - BE record Name
     */
    public void openBudgetEstimate(String budgetEstimateName) {
        filterBudgetEstimateInListPage(budgetEstimateName);
        clickRibbonIcon(RibbonIcons.Edit);
        waitHelper.waitForPageToLoad();
    }

    /**
     * Method to open an existing BE item without filtering (Restricted to rows visible in the page)
     *
     * @param budgetEstimateName - BE item Name
     */
    public void openBudgetEstimateNoFiltering(String budgetEstimateName) {
        waitHelper.waitForPageToLoad();
        singleClickOnRowListPage(getRowNumberFromListPage("Budget Estimate Name", budgetEstimateName));
        clickRibbonIcon(RibbonIcons.Edit);
        waitHelper.waitForPageTabHeaderToBeClickable();
    }

    /**
     * Method for creating new Budget Estimate Items from standard items
     *
     * @param budgetEstimateName - Name of the new Budget Estimate for which budget items will be created
     * @param noOfItems          -     Number of new BE items to be created
     * @return true if all the items are created
     */
    public boolean createBudgetEstimateItemsFromStandardItems(String budgetEstimateName, int noOfItems) {
        openBudgetEstimate(budgetEstimateName);
        return getPage(BudgetEstimateItemsPage.class).createBudgetEstimateItemsFromStandardItems(noOfItems, "Earthwork");
    }

    /**
     * method to edit Budget Estimate
     *
     * @param budgetEstimateName - Name of the budget estimate to be edited
     * @param editedName         Name which is to be updated with.
     */
    public void editBudgetEstimate(String budgetEstimateName, String editedName) {
        openBudgetEstimate(budgetEstimateName);
        getPage(BudgetEstimateDetailsPage.class).editBudgetEstimate(editedName);
    }

    /**
     * To check if Budget Estimate is editable
     *
     * @return -  true if the Budget Estimate is editable
     */
    public boolean isBudgetEstimateEditable() {
        logger().info("Validate if budget estimate is editable");
        waitHelper.waitForPageToLoad();
        navigation.switchFrameToContent();
        return elementHelper.isElementDisplayed(getRibbonIcon(RibbonIcons.More));
    }

    /**
     * Method to perform Auto Forecast of a Budget Estimate
     *
     * @param budgetEstimateName - Name of the Budget Estimate for which Auto Forecast is performed
     */
    public void performBudgetEstimateAutoForecast(String budgetEstimateName) {
        openBudgetEstimateForecastPage(budgetEstimateName);
        if (getPage(ToastUtil.class).validatePresenceOfToastMessage()) {
            getPage(ToastUtil.class).waitAndCloseForSingleToast();
        }
        waitHelper.waitForPageToLoad();
    }

    /**
     * This method changes the forecast status of a Budget Estimate
     *
     * @param budgetEstimateName         - name of the new Budget Estimate
     * @param workFlowAction             - The workflow actions to be performed on the forecast
     * @param expectedStateAfterWFAction - Changes the status of BE forecast
     * @return true if the status is changed for the selected forecast
     */
    public boolean changeBudgetEstimateForecastStatus(String budgetEstimateName, WorkFlowActions workFlowAction, WorkFlowStatus expectedStateAfterWFAction) {
        return getPage(WorkFlowHandler.class).workFlowActionProgression(budgetEstimateName, BudgetEstimateColumnsList.BudgetEstimateName.getValue(), workFlowAction, expectedStateAfterWFAction);
    }

    /**
     * Validates the status of BE Workflow
     *
     * @param budgetEstimateName - name of the new budget estimate
     * @param expectedState      - the state of the new budget estimate after the workflow action is performed
     * @return - true for a successful validation of workflow status
     */
    public boolean validateBudgetEstimateWFStatus(String budgetEstimateName, String expectedState) {
        var rowNum = getRowNumberFromListPage(BudgetEstimateColumnsList.BudgetEstimateName.getValue(), budgetEstimateName);
        return getCellData(rowNum, "Workflow Status").equals(expectedState);
    }

    /**
     * Method to open Budget estimate forecast page
     *
     * @param budgetEstimateName - Budget Estimate Name
     */
    public void openBudgetEstimateForecastPage(String budgetEstimateName) {
        singleClickOnRowListPage(getRowNumberFromListPage(BudgetEstimateColumnsList.BudgetEstimateName.getValue(), budgetEstimateName));
        clickRibbonIcon(RibbonIcons.AllForecastsBudgetEstimate);
        navigation.switchFrameToContent();
        waitHelper.waitForPageTabHeaderToBeClickable();
    }

    /**
     * Method to filter budget estimate list page
     *
     * @param budgetEstimateName - Budget Estimate Name
     */
    public void filterBudgetEstimateInListPage(String budgetEstimateName) {
        waitHelper.waitForPageToLoad();
        waitHelper.waitForPageTabHeaderToBeClickable();
        filterListPage(BudgetEstimateColumnsList.BudgetEstimateName.getValue(), budgetEstimateName, ListPageFilterOptions.Contains);
        singleClickOnRowListPage(0);
        waitHelper.waitForPageToLoad();
    }

    /**
     * Validating the presence and the WF state of the copied BE
     *
     * @param budgetEstimateName - Name of BE to validate
     * @return true if the copied BE item exists in Draft state
     */
    public boolean validateBECopy(String budgetEstimateName) {
        return validateBudgetEstimateWFStatus(budgetEstimateName, WorkFlowStatus.Draft.getValue());
    }

    /**
     * This method creates a new Budget Estimate
     */
    public void createBudgetAndEstimate(String budgetEstimateName) {
        //clickRibbonIcon(RibbonIcons.New); - New button is not available in the Ribbon
        getPage(BudgetEstimateDetailsPage.class).createBudgetEstimate(budgetEstimateName);
        saveAndEstimate();
        navigation.switchFrameToContent();
        waitHelper.waitForPageTabHeaderToBeClickable();
    }

    /**
     * This method creates a new Budget Estimate
     */
    public void createBudgetEstimate(String budgetEstimateName) {
        clickRibbonIcon(RibbonIcons.New);
        getPage(BudgetEstimateDetailsPage.class).createBudgetEstimate(budgetEstimateName);
        getPage(GenericForm.class).clickSave();
        navigation.switchFrameToContent();
        waitHelper.waitForPageTabHeaderToBeClickable();
    }

    /**
     * Click on Save & Estimate
     */
    public void saveAndEstimate() {
        clickRibbonIcon(RibbonIcons.SaveAndEstimate);
        waitHelper.waitForPageToLoad(RibbonIcons.New);
    }

    /**
     * This method creates a new Budget Estimate
     *
     * @param budgetEstimateName   Creates a new Budget Estimate
     * @param documentToBeUploaded File to be uploaded
     */
    public void createBudgetEstimateWithDocumentUpload(String budgetEstimateName, File documentToBeUploaded) {
        clickRibbonIcon(RibbonIcons.New);
        getPage(BudgetEstimateDetailsPage.class).createBudgetEstimateWithDocument(budgetEstimateName, documentToBeUploaded);
        navigation.switchFrameToContent();
        waitHelper.waitForPageTabHeaderToBeClickable();
    }


    /**
     * This method creates a new Budget Estimate
     *
     * @param budgetEstimateName Creates a new Budget Estimate
     * @return true if creation is successful
     */
    public boolean createAndValidateBudgetEstimate(String budgetEstimateName) {
        createBudgetEstimate(budgetEstimateName);
        logger().info("Filtering the newly created BE from the BE List Page");
        filterBudgetEstimateInListPage(budgetEstimateName);
        var filteredBEName = getCellData(0, BudgetEstimateColumnsList.BudgetEstimateName.getValue());
        logger().info("Filtered BE name:" + filteredBEName);
        if (filteredBEName.equals(budgetEstimateName)) {
            logger().pass("Successfully created Budget Estimate with the name " + budgetEstimateName);
            return true;
        } else {
            logger().fail("Failed to create Budget Estimate with the name " + budgetEstimateName);
            return false;
        }

    }

    /**
     * Gets total revenue displayed in Budget Estimate
     *
     * @param budgetEstimateName - Name of the budget estimate for which the total revenue is to be fetched
     * @return - returns the total revenue
     */
    public double getTotalRevenueFromBudgetEstimate(String budgetEstimateName) {
        openBudgetEstimate(budgetEstimateName);
        return getPage(ItemListPage.class).getTotalAmount();
    }


    /**
     * Verify the total measurement systems defined in library is displayed in the budget estimate or not
     *
     * @return - returns true if all measurement systems present in library is displayed in Budget Estimate measure systems dropdown options
     */
    public boolean verifyMeasurementSystemsDisplayed() {
        navigation.switchFrameToContent();
        waitHelper.waitForPageToLoad();
        clickRibbonIcon(RibbonIcons.New);
        waitHelper.waitForPageToLoad();

        select = new Select(elementHelper.getElement(measurementSystemDropdown));
        List<WebElement> dropdownOptions = select.getOptions();
        ArrayList<String> measurementSystemsInBudgetItems = new ArrayList<String>();
        for (WebElement dropdownOption : dropdownOptions) {
            measurementSystemsInBudgetItems.add(dropdownOption.getText());
        }

        navigation.navigateToModule("Library", libraryPage);
        navigation.navigateToFormInLeftPaneTree("Measurement Systems");
        navigation.switchFrameToContent();
        waitHelper.waitForPageToLoad();
        ArrayList<WebElement> list = (ArrayList<WebElement>) elementHelper.getElements(measurementSystemsInLibrary);
        ArrayList<String> measurementSystemsDisplayedInLibrary = new ArrayList<String>();
        for (WebElement element : list) {
            measurementSystemsDisplayedInLibrary.add(element.getText());
        }

        return measurementSystemsInBudgetItems.containsAll(measurementSystemsDisplayedInLibrary);
    }


    /**
     * Verify the hovered text in "Amount in $" column header
     *
     * @return - returns true if the hovered text is as displayed, false otherwise
     */
    public boolean verifyHoverTextOnInflatedBudgetEstimate() {
        navigation.switchFrameToContent();
        waitHelper.waitForPageToLoad();
        String estimateValue = getCellData(1, "Estimate Total in $");
        By totalAmountCell = By.xpath(".//*/div[contains(@title,'This amount represents inflated total from " + estimateValue + ".')]");
        elementHelper.doClick(budgetEstimateCheckBox);
        clickRibbonIcon(RibbonIcons.BudgetEstimateForecast);
        waitHelper.waitForPageToLoad();
        elementHelper.doClick(autoGeneratedForecast);
        clickRibbonIcon(RibbonIcons.Edit);
        elementHelper.doClick(forecastsDetailsTab);
        waitHelper.waitForPageToLoad();
        clickRibbonIcon(RibbonIcons.ShowGantt);
        waitHelper.waitForPageToLoad();
        elementHelper.scrollToView(amountHeader);
        waitHelper.waitForPageToLoad();

        return elementHelper.getElement(totalAmountCell) != null && elementHelper.isElementDisplayed(totalAmountCell);
    }

    /**
     * Compares total revenue displayed in Budget Estimate and Budget Items page
     *
     * @param budgetEstimateName - - Name of the budget estimate for which the revenue are to be compared
     * @return - returns true of the revenues match, false otherwise
     */
    public boolean verifyTotalRevenueInBEAndItemPageAreEqual(String budgetEstimateName) {
        totalRevenueBudgetEstimate = getTotalRevenueFromBudgetEstimate(budgetEstimateName);
        totalRevenueBudgetItems = getPage(BudgetEstimateItemsPage.class).getTotalRevenueFromBudgetItems();
        return (totalRevenueBudgetEstimate == totalRevenueBudgetItems);
    }

    /**
     * Method to fetch data from a specific cell in forecast List page
     *
     * @param rowIdentifier  - row identifier text
     * @param columnToFilter - column to filter with the row identifier
     * @param columnToFetch  - column to fetch the data from
     * @return value corresponding to the column searched
     */
    public String getForecastColumnValue(String rowIdentifier, ForecastListPageColumnsOld columnToFilter, ForecastListPageColumnsOld columnToFetch) {
        logger().info("Fetching the value under the " + columnToFetch.getValue() + " column in forecast page");
        getPage(BudgetEstimateForecastListPage.class).navigateTo();
        var rowNum = getRowNumberFromListPage(columnToFilter.getValue(), rowIdentifier);
        return getCellData(rowNum, columnToFetch.getValue());
    }

    /**
     * ToDo: After Stage merge try catch block not required. Only catch block will validate
     * Get Budget estimate name.
     *
     * @return -   Budget estimate name.
     */
    public String getBudgetEstimateName() {
        String name;
        try {
            waitHelper.waitForPageToLoad(budgetEstimateName);
            name = elementHelper.doGetText(budgetEstimateName);
        } catch (TimeoutException e) {
            waitHelper.waitForPageToLoad(closeBudgetEstimatePopUp);
            getPage(Navigation.class).switchFrameToContent();
            getPage(Navigation.class).switchToSpecificFrame(budgetEstimateFrameID);
            waitHelper.waitForPageToLoad(budgetEstimateName);
            name = elementHelper.doGetText(budgetEstimateName);
        } finally {
            getPage(Navigation.class).switchFrameToDefault();
        }
        return name;
    }

    /**
     * Verify necessary Budget Estimate labels in new form page
     *
     * @param labelsToCompare - the labels to be compared
     * @return - softAssert
     */
    public SoftAssert verifyBudgetEstimateLabelsInNewPage(List<String> labelsToCompare) {
        clickRibbonIcon(RibbonIcons.New);
        waitHelper.waitForPageToLoad();
        var softAssert = new SoftAssert();
        for (String s : labelsToCompare) {
            String labelsDisplayed = String.format(displayedLabels, s);
            softAssert.assertTrue(elementHelper.isElementDisplayed(By.xpath(labelsDisplayed)));
        }
        return softAssert;
    }

    /**
     * Verify Mandatory Budget Estimate labels in new form page
     *
     * @param mandatoryLabels - the mandatory labels to be checked
     * @return - softAssert
     */
    public SoftAssert verifyMandatoryBudgetEstimateLabelsInNewPage(List<String> mandatoryLabels) {
        clickRibbonIcon(RibbonIcons.New);
        waitHelper.waitForPageToLoad();
        var softAssert = new SoftAssert();
        for (String label : mandatoryLabels) {
            String mandatoryLabelsDisplayed = String.format(mandatoryLabel, label);
            softAssert.assertTrue(elementHelper.isElementDisplayed(By.xpath(mandatoryLabelsDisplayed)));
        }
        return softAssert;
    }

    /**
     * Verify Auto populated fields and Estimate Total value
     *
     * @param autoPopulatedLabels - the auto populated labels to be checked
     * @return - true if auto populated labels are and estimate present else return false
     */
    public boolean verifyAutoPopulatedBELabelsAndEstimateTotalInNewPage(List<String> autoPopulatedLabels) {
        clickRibbonIcon(RibbonIcons.New);
        waitHelper.waitForPageToLoad();
        var softAssert = new SoftAssert();
        for (String populatedLabel : autoPopulatedLabels) {
            String autoPopulatedLabelDisplayed = String.format(autoPopulatedLabel, populatedLabel, populatedLabel);
            softAssert.assertTrue(elementHelper.isElementDisplayed(By.xpath(autoPopulatedLabelDisplayed)));
        }
        double estimateTotal = 0.00;
        double displayedEstimateTotal = Double.parseDouble(elementHelper.doGetAttribute(budgetEstimateTotal, "value"));
        softAssert.assertTrue(estimateTotal == displayedEstimateTotal);
        softAssert.assertAll();
        return true;
    }

    /**
     * Verify view functionality of Budget Estimate
     *
     * @param budgetEstimateNameToBeViewed - the budget estimate to be viewed
     * @return - true if the view functionality works as expected
     */
    public SoftAssert validateViewFunctionalityOfBudgetEstimate(String budgetEstimateNameToBeViewed) {
        clearAllFilters();
        singleClickOnRowListPage("Budget Estimate Name", budgetEstimateNameToBeViewed);
        clickRibbonIcon(RibbonIcons.View);
        var softAssert = new SoftAssert();
        softAssert.assertFalse(validateRibbonIcon(RibbonIcons.Save));
        softAssert.assertFalse(elementHelper.isElementDisplayed(budgetEstimateNameID));
        softAssert.assertFalse(elementHelper.isElementDisplayed(budgetEstimateTypeID));
        softAssert.assertFalse(elementHelper.isElementDisplayed(measurementSystemID));
        softAssert.assertFalse(elementHelper.isElementDisplayed(standardItemListID));
        softAssert.assertFalse(elementHelper.isElementDisplayed(descriptionID));
        return softAssert;
    }

    /**
     * Copy Budget Estimate
     *
     * @param budgetEstimateName - budget estimate name to copy
     */
    public void copyBudgetEstimate(String budgetEstimateName) {
        singleClickOnRowListPage(getRowNumberFromListPage(BudgetEstimateColumnsList.BudgetEstimateName.getValue(), budgetEstimateName));
        clickRibbonIcon(RibbonIcons.Copy);
        waitHelper.waitForPageTabHeaderToBeClickable();
    }


    /**
     * Copy a budget estimate and validate the data
     *
     * @param budgetEstimateName - name of the budget estimate to be copied
     * @return - true if the budget estimate is copied, false otherwise
     */
    public boolean validateBudgetEstimateCopy(String budgetEstimateName) {
        clearAllFilters();
        singleClickOnRowListPage("Budget Estimate Name", budgetEstimateName);
        int rowsBeforeCopy = getNumberOfRowsInListPage();

        List<String> columnHeadersToCompare = new ArrayList<>();
        List<String> columnDataToCompare = new ArrayList<>();

        /*
        adding the selective column headers to compare
         */
        columnHeadersToCompare.add(BudgetEstimateColumnsList.BudgetEstimateType.getValue());
        columnHeadersToCompare.add(BudgetEstimateColumnsList.EstimateTotalInDollars.getValue());
        /*
        adding the selective column data to compare
         */
        for (String s : columnHeadersToCompare) {
            columnDataToCompare.add(getCellData(0, s));
        }

        clickRibbonIcon(RibbonIcons.Copy);
        waitHelper.waitForPageToLoad();
        clearAllFilters();

        Iterator<String> headerIterator = columnHeadersToCompare.iterator();
        Iterator<String> dataIterator = columnDataToCompare.iterator();
        while (headerIterator.hasNext() && dataIterator.hasNext()) {
            waitHelper.waitForPageToLoad();
            filterListPage(headerIterator.next(), dataIterator.next(), ListPageFilterOptions.Contains);
        }
        int rowsAfterCopy = getNumberOfRowsInListPage();
        return rowsAfterCopy > rowsBeforeCopy;
    }

    /**
     * Validate Budget Estimate column headers displayed in list page and customized list
     *
     * @return - header comparison
     */
    public boolean validateBudgetEstimateColumnsInListPage() {
        logger().info("Validate Budget Estimate column headers displayed in list page and customized list");
        List<String> allColumnHeadersDisplayed = getListPageHeaders();
        List<String> listPageColumnsExpected = BudgetEstimateColumnsList.getList();
        return allColumnHeadersDisplayed.containsAll(listPageColumnsExpected);
    }

    /**
     * Validate Excel Data Exported
     *
     * @param fileName           - name of the file exported
     * @param node               - host node
     * @param budgetEstimateName - budget estimate name to be verified
     * @return - true if the excel values and headers matches with the list page
     */
    public boolean validateExcelDataExport(String fileName, Host node, String budgetEstimateName) {
        List<String> budgetEstimateColumnHeaders = getListPageHeaders();
        List<String> budgetEstimateRowValues = new ArrayList<>();

        Map<String, String> listPageColumnHeadersWithValues = new HashMap<>();
        int budgetEstimateRowNumber = getRowNumberFromListPage(BudgetEstimateColumnsList.BudgetEstimateName.getValue(), budgetEstimateName);

        for (int i = 0; i < budgetEstimateColumnHeaders.size(); i++) {
            budgetEstimateRowValues.add(getCellData(budgetEstimateRowNumber, budgetEstimateColumnHeaders.get(i)));
            listPageColumnHeadersWithValues.put(budgetEstimateColumnHeaders.get(i), budgetEstimateRowValues.get(i));
        }
        Map<String, String> excelColumnHeadersWithValue =
                ExcelUtil.getColumnHeadersWithRowData(fileName, node, BudgetEstimateColumnsList.BudgetEstimateName.getValue(), budgetEstimateName, null);

        for (Map.Entry<String, String> entry : listPageColumnHeadersWithValues.entrySet()) {
            String key = entry.getKey();
            switch (key) {
                case "Release To Planning":
                    listPageColumnHeadersWithValues.replace("Release To Planning", "False");
                    break;
                default:
                    break;
            }
        }
        return listPageColumnHeadersWithValues.equals(excelColumnHeadersWithValue);
    }

    /**
     * Delete a budget estimate
     *
     * @param budgetEstimateName - name of the budget estimate to be deleted
     * @return - true if budget estimate is deleted
     */
    public boolean deleteBudgetEstimate(String budgetEstimateName) {
        singleClickOnRowListPage(getRowNumberFromListPage(BudgetEstimateColumnsList.BudgetEstimateName.getValue(), budgetEstimateName));
        clickRibbonIcon(RibbonIcons.Delete);
        getPage(AlertHandler.class).acceptAlert(true);
        waitHelper.waitForPageTabHeaderToBeClickable();
        return getRowNumberFromListPage(BudgetEstimateColumnsList.BudgetEstimateName.getValue(), budgetEstimateName) == -1;
    }

    /**
     * Validate Attachment Functionality in Ribbon for Budget Estimate
     *
     * @param fileName - name of the file
     * @return - true if file name is displayed
     */
    public SoftAssert validateAttachmentFunctionalityRibbon(String fileName) {
        logger().info("Validate Attachment Functionality in Ribbon for Budget Estimate");
        waitHelper.waitForPageToLoad();
        clickRibbonIcon(RibbonIcons.Attachment);
        waitHelper.waitForPageToLoad();
        return getPage(Attachments.class).validateAttachmentByName(fileName, true);
    }

    /**
     * Validating budget Template
     *
     * @param budgetTemplate Name of the budget Template
     * @return True if the budget Template exists
     */
    public boolean validateBudgetTemplate(String budgetTemplate) {
        navigation.switchFrameToContent();
        waitHelper.waitForPageToLoad();
        elementHelper.doClick(budgetTemplateButton);
        waitHelper.waitForPageToLoad();
        By budgetTemplateFilter = By.xpath(String.format("//div[contains(@id,'%s')]", elementHelper.getLocatorAsString(budgetTemplatePicker)));
        waitHelper.waitForElementPresent(budgetTemplatePicker);
        getPage(Picker.class).filterPickerColumn(budgetTemplateFilter, "Template Name", budgetTemplate, PickerFilterOptions.Contains);
        return getPage(Picker.class).getColumnData(budgetTemplatePicker, "BudgetTemplateName", 1).contains(budgetTemplate);
    }

    /**
     * Validate Inflation Highlight Details Page
     *
     * @return - true if inflation rule is highlighted
     */
    public boolean validateInflationHighlightDetailsPage() {
        logger().info("Validate Inflation Highlight Details Page");
        waitHelper.waitForPageToLoad();
        return elementHelper.isElementDisplayed(inflationHighlightBEDetailsPage);
    }

    /**
     * Validate Inflation Highlight List Page
     *
     * @return - true if inflation rule is highlighted
     */
    public boolean validateInflationHighlightListPage() {
        logger().info("Validate Inflation Highlight List Page");
        waitHelper.waitForPageToLoad();
        return elementHelper.isElementDisplayed(inflationHighlightBEListPage);
    }

    /**
     * Validate Inflation Applied
     *
     * @return - true if inflation is applied
     */
    public boolean validateInflationApplied() {
        logger().info("Validate Inflation Applied");
        waitHelper.waitForPageToLoad();
        double inflatedAmount = Double.parseDouble(getCellData(0, BudgetEstimateColumnsList.InflatedEstimateTotalInDollars.getValue()).replaceAll(RegexStrings.notDigitOrDot.getValue(), ""));
        double totalAmount = Double.parseDouble(getCellData(0, BudgetEstimateColumnsList.EstimateTotalInDollars.getValue()).replaceAll(RegexStrings.notDigitOrDot.getValue(), ""));
        return (inflatedAmount != totalAmount);
    }

    /**
     * Method to validate Forecast created for BE Revision
     *
     * @param budgetEstimateName - Name of the Budget Estimate Revision for which Forecast is created
     * @return true if forecast is created
     */
    public boolean validateForecast(String budgetEstimateName) {
        waitHelper.waitForPageToLoad();
        var rowNum = getRowNumberFromListPage(ForecastListPageColumns.ForecastName.getValue(), budgetEstimateName);
        return rowNum > -1;
    }
}
