package com.aurigo.masterworks.testframework.webUI.constants.enums;

import java.util.ArrayList;
import java.util.List;

public enum AuditLogFormFields {
    TaskID("Task ID"),
    CheckAll("Check All"),
    TaskName("Task Name"),
    TaskDetails("Task Details"),
    LineNumber("Line Number"),
    TaskSchedule("Task Schedule"),
    ResourceTitle("Resource Title"),
    PayItemNo("Pay Item No."),
    BudgetItem("Budget Item"),
    ForecastsItemDetails("Forecast Item Details"),
    FundingRule("Funding Rule"),
    GanttDetails("Gantt Details"),
    Item("Item"),
    ProgramCode("Code"),
    ProjectCode("Project Code"),
    Start("Start"),
    End("End"),
    Container("Container"),
    ContainerName("Container Name"),
    TitleID("Title ID"),
    Title("Title"),
    Resources("Resources"),
    FullName("Full Name"),
    ForecastsDetails("Forecast Details"),
    ForecastsDuration("Forecast Duration"),
    Description("Description"),
    Weightage("Weightage"),
    Complete("Complete"),
    Notes("Notes"),
    ItemDesciption("Item Description"),
    InflationRule("Inflation Rule"),
    Amount("Amount"),
    StartDate("Start Date"),
    EndDate("End Date"),
    NoOfDays("No. of Days"),
    Duration("Duration"),
    PercentageComplete("% Complete"),
    ProgressPercentage("Progress %"),
    Predecessor("Predecessor"),
    Program("Program"),
    SubItem("Sub Item"),
    Subject("Subject"),
    To("To"),
    Name("Name"),
    ChangeOrderDetails("Change Order Details"),
    ShortDescription("Short Description"),
    BidLettingID("ID"),
    BidAdvertisementDate("Bid Advertisement Date"),
    BidIssueDate("Bid Issue Date"),
    AddendumIssueDate("Addendum Issue Date"),
    PreBidMeetingDate("Pre-Bid Meeting Date"),
    BidOpeningDateTime("Bid Opening Date and Time"),
    BidDueTime("Bid Due Time"),
    Address("Address"),
    BidLetting("Bid Letting"),
    Type("Type"),
    Status("Status"),
    Projects("Projects"),
    Programs("Programs"),
    PlannedLands("Planned Lands"),
    ProgramBudget("Program Budget"),
    MaterialsOnHand("Materials On Hand"),
    ApprovedOn("Approved On"),
    MOHDate("MOH Date"),
    Comments("Comments"),
    Material("Material"),
    AmountIn$("Amount in $"),
    ContractItems("Contract Items"),
    RecoveryInQuantity("Recovery Quantity"),
    LinkedRecords("Linked Records"),
    RecordIdentifier("Record Identifier"),
    FundSource("Fund Source"),
    FundCategory("Fund Category"),
    ContractName("Contract Name"),
    SourceForm("Source Form"),
    Quantity("Quantity"),
    ProjectStatus("Project Status"),
    ProjectScore("Project Score"),
    ProgramYear("Program Year"),
    ProgramType("Program Type"),
    TotalCost$("Total Cost ($)"),
    DefaultFiscalYear("Default Fiscal Year"),
    ProgramCategory("Program Category"),
    LandCost$("Land Cost ($)"),
    ProjectsCount("Projects Count"),
    ProgramsCount("Programs Count"),
    MinCost$("Min Cost ($)"),
    MaxCost$("Max Cost ($)"),
    PlanningFund("Planning Fund"),
    ProgramBudget$("Program Budget ($)"),
    Remaining$("Remaining ($)"),
    Cost$("Cost ($)"),
    ForecastDuration("Forecast Duration"),
    ResourceTitles("Resource title(s)"),
    ResourceDepartments("Resource Departments"),
    ResourceDepartment("Resource Department"),
    EnterpriseResourceDirectory("Enterprise Resource Directory"),
    ResourceID("Resource ID"),
    ResourceTitlesLibrary("Resource Titles"),
    Transmittals("Transmittals"),
    TransmittalTemplate("Transmittal Template"),
    SubmittalPackage("Submittal Package"),
    PackageTitle("Package Title"),
    Submittals("Submittals"),
    SubmittalTitle("Submittal Title"),
    SubmittalID("Submittal ID"),
    BidItems("Bid Items"),
    UnitPriceIn$("Unit Price in $"),
    TableName("Table Name"),
    AddStandardTable("Add Standard Table"),
    Component("Component"),
    ComponentName("Component Name"),
    MailMergeConfiguration("Mail Merge Configuration"),
    Groups("Groups"),
    FormBuilder("Form Builder"),
    FormID("Form ID"),
    Header("Header"),
    DocumentFolderStructure("Document Folder Structure"),
    DocumentFolderStructureName("Document Folder Structure Name"),
    AssociatedFolders("Associated Folders"),
    MasterContracts("Master Contracts"),
    WorkOrders("Work Orders"),
    PayEstimates("Pay Estimates"),
    PayEstimateNumber("Pay Estimate Number"),
    GlobalFundList("Global Fund List"),
    ResourceTypes("Resource Types"),
    ProjectFundTransaction("Project Fund Transaction"),
    FundTransaction("Fund Transaction"),
    MeetingAgenda("Meeting Agenda"),
    MeetingType("Meeting Type"),
    MinutesOfMeeting("Minutes Of Meeting"),
    VenueOthers("Venue Others"),
    Sequence("Sequence"),
    IssuePriority("Issue Priority"),
    IssueType("Issue Type"),
    RiskCategory("Risk Category"),
    RiskColor("Risk Color"),
    RiskProbability("Risk Probability"),
    RiskSeverity("Risk Severity"),
    SecurityRoles("Security Roles"),
    VendorCategory("Vendor Category"),
    VendorCategoryToReviewStages("Vendor Category to Review Stages"),
    VendorEvaluationCategoryProject("Vendor Evaluation Category (Project)"),
    MasterContractCategory("Master Contract Category"),
    AllowMasterContractApproval("Allow Master Contract Approval Without Item(s)"),
    Pono("PO No."),
    PurchaseOrder("Purchase Order"),
    Category("Category"),
    BidManagement("Bid Management"),
    PurchaseOrderRevision("Purchase Order Revision"),
    LeadTimeInDays("Lead Time in Days"),
    PayItemNew("Pay Items (Type-New)"),
    PayItemModify("Pay Items (Type-Modify Existing)"),
    VendorScoringCategory("Vendor Scoring Category (Enterprise)"),
    DistributionDetails("Distribution Details"),
    DocumentProperties("Document Properties"),
    BudgetEstimateType("Budget Estimate Type"),
    PayItems("Pay Items"),
    PurchaseOrderAttachments("Purchase Order - Attachments"),
    GroupDetails("Group details"),
    AlternateDetails("Alternate details");


    private String value;

    AuditLogFormFields(String value) {
        this.value = value;
    }

    /**
     * Method to get the list of items from the enum
     *
     * @return list of Audit log Form Fields
     */
    public static List<String> getList() {
        List<String> listToReturn = new ArrayList<>();
        for (var item : AuditLogFormFields.values()) {
            listToReturn.add(item.getValue());
        }
        return listToReturn;
    }

    public String getValue() {
        return this.value;
    }
}
