package com.aurigo.masterworks.testframework.webUI.constants.enums;

import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public enum FormBuilderSimpleInputControlSimpleMode {

    AutoGenerated("Auto Generated"),
    SingleLineText("Single Line Text"),
    MultiLineText("Multi Line Text"),
    Date("Date"),
    Numeric("Numeric"),
    Integer("Integer"),
    TimeInput("Time Input"),
    DropDown("Drop Down"),
    ListBox("List Box"),
    CheckBoxList("Check Box List"),
    CheckBox("Check Box"),
    RadioButtonList("Radio Button List"),
    FormattedInput("Formatted Input"),
    Password("Password"),
    Label("Label"),
    Hidden("Hidden"),
    DateTime("Date Time"),
    TimeInputPicker("Time Input Picker");

    private final String value;

    FormBuilderSimpleInputControlSimpleMode(String value) {
        this.value = value;
    }

    /**
     * Method to get the list of items from the enum
     *
     * @return list of Enum values
     */
    public static List<String> getList() {
        List<String> enumValues = Stream.of(FormBuilderSimpleInputControlSimpleMode.values())
                .map(e -> e.getValue())
                .collect(Collectors.toList());
        return enumValues;
    }

    public String getValue() {
        return this.value;
    }
}
