package com.aurigo.masterworks.testframework.webUI.constants.enums;
import java.util.ArrayList;
import java.util.List;

/**
 * List of texts of the column names in the Work Project list page
 */
public enum WorkProjectPageColumns {

    AutoGeneratedID("Auto Generated ID"),
    Name("Name"),
    Description("Description"),
    ID("ID"),
    ProgramYear("Program Year"),
    BusinessUnit("Business Unit"),
    EstimatedCost("Estimated Cost($)"),
    ProgramCategory("Program Category");

    // declaring private variable for getting values
    private String value;

    WorkProjectPageColumns(String value) {
        this.value = value;
    }

    /**
     * method to return the list of the column names
     *
     * @return list of the column names
     */
    public static List<String> getListOfColumnNames() {
        var listToReturn = new ArrayList();
        for (var item : WorkProjectPageColumns.values()) {
            listToReturn.add(item.getValue());
        }
        return listToReturn;
    }

    public String getValue() {
        return this.value;
    }

}
